/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EChart: typeof import('./src/components/EChart.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    PaginationTable: typeof import('./src/components/PaginationTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
